services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Letkode\DataProviderBundle\:
        resource: '../src/'
        exclude:
            - '../src/LetkodeDataProviderBundle.php'
            - '../src/Attribute/'
            - '../src/Exception/'
